export const assets = [
    {url:"./terry.png", name:"normalTerry"},
    {url:"./caña.png", name:"normalcania"},
    {url:"./cielo.jpg", name:"normalCielo"},
    {url:"./fondoAgua.jpg", name:"normalAgua"},
    {url:"./fondoTierraEditado.png", name:"normalTierra"},
    {url:"./Pez.png", name:"normalPez"},
    {url:"./botonSF.png", name:"normalBoton"},
    {url:"./botonSFdown.png", name:"downButton"},
    {url:"./botonSFover.png", name:"overButton"},
    {url:"./estrellaLlenaSF.png", name:"normalEstrellaL"},
    {url:"./estrellaVaciaSF.png", name:"normalEstrellaV"},
    {url:"./tableroSF.png", name:"normalTablero"},
    {url:"./cartelChicoSF.png", name:"normalCartelito"},
    {url:"./nada.png", name:"nada"},
    {url:"Swim_to_right/1.png", name:"normalFish1"},
    {url:"Swim_to_right/2.png", name:"normalFish2"},
    {url:"Swim_to_right/3.png", name:"normalFish3"},
    {url:"Swim_to_right/4.png", name:"normalFish4"},
    {url:"Swim_to_right/5.png", name:"normalFish5"},
    {url:"Swim_to_right/6.png", name:"normalFish6"},
    {url:"dvd.png", name:"normalDVD"},
    {url:"anzueloSF.png", name:"normalHook"}
];